"""empty message

Revision ID: 8432e3944557
Revises: 10e2d96b1600
Create Date: 2022-12-11 16:25:55.225650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8432e3944557'
down_revision = '10e2d96b1600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('resumo', sa.String(length=100), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipoenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operacao')
    # ### end Alembic commands ###
