"""empty message

Revision ID: c9b84a39485b
Revises: ded4771989a8
Create Date: 2022-12-13 10:48:39.195344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b84a39485b'
down_revision = 'ded4771989a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conta', 'usuario', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conta', type_='foreignkey')
    op.drop_column('conta', 'usuario_id')
    # ### end Alembic commands ###
